spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  ftp:
    host: 127.0.0.1
    port: 21
    username: ftpuser
    password: ftpuser
  mail:
    host: smtp.163.com
    username: j150714101@163.com
    password: jm19930913
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/demo

eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@${spring.cloud.client.ip-address}:9000/eureka/